version: "3"

services:
  redis:
    image: "redis:alpine"
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./image_comparsion:/image_comparsion
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  celery:
    build: .
    command: celery -A image_comparsion worker -l info
    volumes:
      - ./image_comparsion:/image_comparsion
    depends_on:
      - db
      - redis